"""Generate the colour style sheets from :mod:`spiffyplots.colors`.

.. code-block:: console

    python -m spiffyplots._genstyles           # rewrite the sheets
    python -m spiffyplots._genstyles --check   # fail if they are out of date
"""

import argparse
import sys
from pathlib import Path

from . import colors

#: Where the colour sheets are written.
COLOR_STYLES_PATH = Path(__file__).parent / "styles" / "color"

TOL_URL = "https://sronpersonalpages.nl/~pault/"
OKABE_ITO_URL = "https://jfly.uni-koeln.de/color/"

# filename stem -> (scheme, title, credit)
SHEETS = {
    "tol-bright": (colors.tol_bright, "Paul Tol's bright scheme", TOL_URL),
    "tol-high-contrast": (
        colors.tol_high_contrast,
        "Paul Tol's high-contrast scheme",
        TOL_URL,
    ),
    "tol-light": (colors.tol_light, "Paul Tol's light scheme", TOL_URL),
    "tol-medium-contrast": (
        colors.tol_medium_contrast,
        "Paul Tol's medium-contrast scheme",
        TOL_URL,
    ),
    "tol-muted": (colors.tol_muted, "Paul Tol's muted scheme", TOL_URL),
    "tol-vibrant": (colors.tol_vibrant, "Paul Tol's vibrant scheme", TOL_URL),
    "okabe-ito": (colors.okabe_ito, "Okabe and Ito (2002)", OKABE_ITO_URL),
}


def render(scheme, title: str, credit: str) -> str:
    """The text of one sheet."""
    values = ", ".join(f"'{color.lstrip('#')}'" for color in scheme)
    return "\n".join(
        [
            f"# {title}. {len(scheme)} colours, colour-blind safe.",
            f"# Order: {', '.join(scheme.names)}.",
            f"# Credit: {credit}",
            "#",
            "# Generated from spiffyplots.colors by `python -m spiffyplots._genstyles`.",
            "# Edit the colour data there, not this file.",
            "",
            f"axes.prop_cycle : cycler('color', [{values}])",
            "",
        ]
    )


def generate() -> dict[str, str]:
    """Every sheet's filename mapped to its text."""
    return {
        f"{stem}.mplstyle": render(*definition) for stem, definition in SHEETS.items()
    }


def main(argv: list[str] | None = None) -> int:
    """Write the sheets, or check the shipped ones are up to date."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if any sheet is out of date",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=COLOR_STYLES_PATH,
        help=f"directory to write into (default: {COLOR_STYLES_PATH})",
    )
    args = parser.parse_args(argv)

    sheets = generate()
    problems = []

    for filename, text in sheets.items():
        path = args.output / filename
        current = path.read_text() if path.is_file() else None
        if current == text:
            continue
        if args.check:
            problems.append(f"out of date: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {path}")

    if args.output.is_dir():
        unexpected = sorted(
            path.name
            for path in args.output.glob("*.mplstyle")
            if path.name not in sheets
        )
        problems += [
            f"not generated by this script: {args.output / name}" for name in unexpected
        ]

    for problem in problems:
        print(problem, file=sys.stderr)
    if problems:
        print("Run `python -m spiffyplots._genstyles` to regenerate.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
