language: python
python:
- 3.8
- 3.7
- 3.6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov

install:
    - pip install -r requirements.txt
    - pip install ".[test]" # install package + test dependencies

script:
    - pytest

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  skip_existing: true
  password: pypi-AgEIcHlwaS5vcmcCJDEyMTdmOGZlLWY4MmYtNDI1OC1hNzgxLTYzMWJkZDZiMWZmZgACPHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJzcGlmZnlwbG90cyJdfSwgInZlcnNpb24iOiAxfQAABiDIbj03wm1aP3z5VBxO_mN-_WlFOaGbGBS6zEjdJyeYoA
  on:
    tags: true
    repo: JRBCH/spiffyplots
    python: 3.8
