language: python
python:
- 3.8
- 3.7
- 3.6

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install -r requirements.txt

install:
    - pip install ".[test]" # install package + test dependencies

script:
    - pytest

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist
  user: JRBCH
  password:
    secure: c6qbp1x9+v0kY1or7VsC4qN1410p4wd4Qug4yeKiVFmT2eV9qwSiEgcW2C3yhsd+wVUcSgmgEIKqpiK0CNeYO+CLvRcQ3gK3UP/p4l8sBZ7iUxD3U/p7W+HcRGehT2hV4aRPuIF1lexDkTtMT+c0ssMPfWToMK6/BQqRpnlnclXSezRR55r2QYFtfMZnTIDdxtkuokRrKEVT+wsSDBbd/YFSNLQDKY2JvDVUggJGSmU4D262iMBnt/Wt8mT05rbem1MLZxAhX55sgg3EW3VmqT3wWkWxcEv77pAZdpKUBFrIh2uiibpJyEAorcxbz+NvBSIHbpJ2BvDD78uIm0aEHgYkHa2gGjK1/Pv/AwD0BaVDUTBs5JF0PVEY9VyBXCMOqKRtLwE7ycVRwusRkPC/Kh1CNENWkQJtRnJnv6hl5W+Mjp5uyrAG1rNL/N09XSbij1t5umelZaMi1djhI24zKJJVdXES/PCkjPWbt2QdE2beETGAvBQ2xzIKU5Tco+dOB7fUTCbv0e0wts8PIWF3S6uuG7DRf/LCc39Ut8wK2KMVMwPotXU/WruM2tXRDhJLa9keJi+LeVyxBS/mAr84B6tY21xfz8EhtBWLX5HCUTt3e6qssd5BNEhn5Sl5uLFRvdXE/qBu5Cpo+hl4yMSVk4FDZoUDUfyv8FmGqThJy28=
  on:
    tags: true
    repo: JRBCH/spiffyplots
    python: 3.8
